name: 'Checkout Node Project'
description: 'Checkout, install Node, and run `npm ci`'

inputs:
  node-version:
    description: Node.js version to install
    required: false
    default: 20.x

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{inputs['node-version']}}

    - name: Install dependencies
      run: npm ci
      shell: bash
